# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Return-DataButBool
version:      v0.0.2
version_from: lib/Return/DataButBool.pm
installdirs:  site
requires:
    Contextual::Return:            0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
